### PR TITLE
Test against latest FastAPI

### PR DESCRIPTION
**Pull request by toph-allen**
## Description

CI adjustments.

- Added Python 3.12 to all workflows.
- Added a new workflow, "Test Latest FastAPI", which sets up a dev environment and runs tests. It is similar to the CI workflow, with a few differences:
  - Skips linting.
  - Before running the tests, it runs `pip install --upgrade fastapi`, which installs the latest FastAPI, despite it being pinned by FastAPI-Tableau to an earlier version.
  - Scheduled to run every Monday at 1:00 PM UTC (9 AM EDT).

Ideally, this workflow will fail when we break on the latest FastAPI, giving us a heads-up that updating to the latest FastAPI will require changes.

Right now, Pip prints a message about the dependency conflict but does not prevent the upgrade. It is possible that future versions of Pip will prevent this "breaking" upgrade. If that happens, we might need to use a tool like [tox](https://tox.wiki/en/latest/).

## Testing Notes / Validation Steps

N/A; CI change only.

### CODE REVIEW

**Comment by toph-allen** [comment]
Unsure why the latest commit didn't trigger GH Actions to run.

**Review by sagerb — APPROVED** [review]
LGTM!

**Comment by ChaitaC** [comment]
CI passed, no additional testing required.

**Comment by blairj09** [comment]
I meant to add this before it was merged, but just wanted to confirm that Toph and I tested against Tableau desktop with a local extension as well as an extension hosted on Posit Connect and everything behaved as expected 🙌

**Pull request merged**
